-- ============================================================
-- Tripolar 种子数据 — AI 视频工具目录 (100 条)
-- 表: ai_product_types / ai_use_cases / ai_tools
-- 数据来源: docs/AI视频工具全量清单 (100个).md
-- 执行: psql -U tripolar -d tripolar -f sql/03_seed_ai_tools.sql
-- ============================================================

BEGIN;

-- -----------------------------------------------------------
-- 产品类型
-- -----------------------------------------------------------
INSERT INTO ai_product_types (name, slug, description, sort_order) VALUES
    ('AI编程工具', 'ai-coding-tools',  '辅助开发者写代码、读代码、调试和重构的AI工具', 10),
    ('AI视频工具', 'ai-video-tools',   '用于视频生成、剪辑、字幕、特效和内容制作的AI工具', 20),
    ('AI写作工具', 'ai-writing-tools', '用于文章、营销文案、邮件、脚本等文本创作的AI工具', 30),
    ('AI图像工具', 'ai-image-tools',   '用于图片生成、编辑、设计和视觉创作的AI工具', 40),
    ('AI办公工具', 'ai-office-tools',  '用于文档、表格、PPT、会议和协作效率提升的AI工具', 50)
ON CONFLICT (slug) DO NOTHING;

-- -----------------------------------------------------------
-- 使用场景
-- -----------------------------------------------------------
INSERT INTO ai_use_cases (name, slug, description, sort_order) VALUES
    ('代码生成',       'code-generation',            '根据自然语言或上下文生成代码',                         10),
    ('视频生成',       'video-generation',           '根据提示词、图片或其他素材生成视频内容',               10),
    ('视频创作',       'video-creation',             '综合视频内容创作，包括策划、制作和输出',               15),
    ('代码补全',       'code-completion',            '在编码过程中智能补全代码',                             20),
    ('视频剪辑',       'video-editing',              '剪辑、拼接、调整和处理视频内容',                       20),
    ('电商视频制作',   'ecommerce-video-creation',    '面向电商商品展示、营销投放和带货场景的视频制作',       25),
    ('数字人制作',     'digital-human-creation',      '创建虚拟数字人形象并生成口播、交互或表演视频',        30),
    ('动画制作',       'animation-creation',          '生成动画风格的视频内容，包括二次元、漫画等',           35),
    ('视频翻译/本地化','video-localization',          '视频翻译、配音替换和多语言本地化处理',                 40),
    ('字幕生成',       'subtitle-generation',         '自动识别语音并生成字幕',                               40),
    ('视频广告制作',   'video-ad-creation',           '面向广告投放和营销推广场景的视频素材制作',             45),
    ('短剧创作',       'short-drama-creation',        '创作漫剧、短剧或系列化叙事视频内容',                   50),
    ('文案写作',       'copywriting',                 '生成营销文案、社媒文案、广告语等内容',                 50),
    ('内容创作',       'content-creation',            '面向自媒体、图文转视频等内容创作需求',                 55),
    ('视觉创作',       'visual-creation',             '综合视觉内容创作，包括图像和视频的艺术化生成',         60),
    ('文章写作',       'article-writing',             '生成长文章、博客、SEO文章等内容',                      60),
    ('知识视频制作',   'knowledge-video-creation',    '将文档、知识内容转化为结构化讲解视频',                 65),
    ('创意设计',       'creative-video-design',       '视频风格化、创意设计和艺术化处理',                     70),
    ('图片生成',       'image-generation',            '根据提示词生成图片',                                   70),
    ('PPT生成',        'presentation-generation',     '根据主题或文档生成演示文稿',                           80),
    ('文档问答',       'document-qa',                 '基于文档内容进行问答和总结',                           90)
ON CONFLICT (slug) DO NOTHING;

-- -----------------------------------------------------------
-- AI 视频工具 — 100 条
-- -----------------------------------------------------------

INSERT INTO ai_tools
    (name, slug, company, product_type_id, primary_use_case_id, short_description, overview, website_url, status)
VALUES
    ('LibTV',            'libtv',                  'LiblibAI',   (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-generation'),            '专业AI视频创作平台',          '支持Seedance 2.0满血版，提供极高保真度的视频生成与真人参考功能。',                                                  'https://www.liblib.art/video',                 'active'),
    ('绘蛙AI视频',       'huiwa-ai-video',         '阿里巴巴',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'ecommerce-video-creation'),    'AI图生视频工具',              '阿里推出的针对电商场景的AI视频工具，支持商品图一键转视频。',                                                         'https://www.huiwa.com/',                       'active'),
    ('堆友AI视频',       'duiyou-ai-video',        '阿里巴巴',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'creative-video-design'),       'AI视频生成工具',              '堆友旗下的AI视频模块，支持多种艺术风格的视频转化与生成。',                                                           'https://duiba.com.cn/',                        'active'),
    ('SoundView',        'soundview',              NULL,          (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-localization'),          'AI视频翻译/声音克隆',         '专注于视频本地化，提供高质量的视频翻译与原声克隆服务。',                                                             'https://soundview.ai/',                        'active'),
    ('蝉镜',             'chanjing',               '蝉妈妈',      (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'digital-human-creation'),      'AI数字人视频生成平台',         '蝉妈妈推出的数字人平台，适合快速制作口播带货视频。',                                                                 'https://www.chanjing.com/',                     'active'),
    ('HeyGen',           'heygen',                 'HeyGen',     (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'digital-human-creation'),      '专业的AI数字人视频创作平台',    '全球领先的数字人平台，支持多语言翻译及极高真实度的数字人生成。',                                                      'https://www.heygen.com/',                       'active'),
    ('LiblibAI',         'liblibai',               '哩布哩布',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'content-creation'),            '一站式 AI 内容创作生成平台',   '国内领先的AIGC社区，集成图像与视频生成能力。',                                                                      'https://www.liblib.art/',                       'active'),
    ('有言',             'youyan',                 '魔珐科技',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'digital-human-creation'),      '3D数字人AI视频生成平台',       '无需拍摄剪辑，输入文字即可生成高质量3D数字人视频。',                                                                'https://www.youyan3d.com/',                     'active'),
    ('白日梦',           'bai-ri-meng-ai',         '白日梦AI',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-generation'),            '领先AI视频创作平台',           '支持生成最长50分钟的视频，覆盖从新手到专业的全场景创作。',                                                           'https://aibrm.com/',                            'active'),
    ('即梦AI',           'jimeng-ai',              '字节跳动',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-generation'),            '一站式AI视频、图片、数字人创作工具', '字节跳动推出的全能型AI创作工具，集成多种领先模型。',                                                                 'https://jimeng.jianying.com/',                  'active'),
    ('Pollo AI',         'pollo-ai',               'Pollo AI',   (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-generation'),            '一站式AI图像和视频创作平台',    '整合多种顶级AI模型，提供高分辨率的视频与图像生成服务。',                                                             'https://pollo.ai/',                             'active'),
    ('Seedance',         'seedance',               '字节跳动',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-generation'),            '多模态 AI 视频生成模型',       '字节Seed团队推出，支持文字、图片、音频、视频四种模态输入。',                                                         'https://seed.bytedance.com/',                   'active'),
    ('魔珐星云',         'mofaxingyun',            '魔珐科技',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'digital-human-creation'),      '具身智能3D数字人开放平台',     '专注于3D数字人的实时交互与开放生态建设。',                                                                          'https://www.mofage.com/',                       'active'),
    ('JoyPix',           'joypix',                 'JoyPix',     (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'digital-human-creation'),      'AI数字人创作工具',             '支持将照片转化为会说话的数字人，特别擅长动漫风格。',                                                                  'https://www.joypix.ai/',                        'active'),
    ('可灵AI',           'kling-ai',               '快手',       (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-generation'),            '快手推出的AI视频生成工具',      '国内顶尖的视频生成模型，支持长达2分钟的视频生成。',                                                                   'https://klingai.kuaishou.com/',                 'active'),
    ('Vidu',             'vidu',                   '生数科技',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-generation'),            'AI视频生成大模型',             '清华系团队推出，具备极强的物理规律模拟能力。',                                                                        'https://www.vidu.ai/',                          'active'),
    ('腾讯混元AI视频',   'hunyuan-ai-video',       '腾讯',       (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-generation'),            '腾讯推出的AI视频生成工具',      '腾讯混元大模型旗下的视频生成产品，支持电影级画质输出。',                                                              'https://video.hunyuan.tencent.com/',            'active'),
    ('通义万相AI视频',   'tongyi-wanxiang-video',  '阿里巴巴',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-generation'),            '阿里推出的AI视频生成工具',      '阿里通义旗下的AI创意平台，支持多种视频创作场景。',                                                                    'https://tongyi.aliyun.com/wanxiang/',           'active'),
    ('雾象 (Fogsight)',  'fogsight',               '雾象团队',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'animation-creation'),          '免费开源的AI动画生成工具',      'LLM驱动的动画引擎，适合制作科普、解说类二维动画。',                                                                   'https://fogsight.ai/',                          'active'),
    ('TapNow',           'tapnow',                 'TapNow',     (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'visual-creation'),             'AI视觉内容创作平台',           '基于无限画布设计，提供多种预设工作流，适合专业影视创作。',                                                             'https://tapnow.com/',                           'active'),
    ('Higgsfield',       'higgsfield',             'Higgsfield', (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-generation'),            'AI视频生成工具',               '支持专业级运镜效果，致力于将简单创意转化为电影质感视频。',                                                             'https://higgsfield.ai/',                        'active'),
    ('Flova',            'flova',                  'Flova AI',   (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-creation'),              '一体化 AI 视频创作平台',        '全球首个集构思、分镜、拍摄、剪辑于一体的AI视频创作平台。',                                                            'https://www.flova.ai/',                         'active'),
    ('Zorq AI',          'zorq-ai',                'Zorq AI',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-creation'),              '多模型聚合 AI 创意生成平台',    '聚合多种顶级AI模型，提供视频、图像、语音一站式生成。',                                                                'https://zorqai.com/',                           'active'),
    ('Pexo',             'pexo',                   'Pexo AI',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-creation'),              'AI 视频创作Agent',            '通过自然语言对话生成视频，无需复杂剪辑操作。',                                                                        'https://pexo.ai/',                              'active'),
    ('Topview',          'topview-ai',             'Topview AI', (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'ecommerce-video-creation'),    '电商与营销场景 AI 视频生成Agent', '专为电商打造，支持从商品链接一键生成高转化广告视频。',                                                                'https://www.topview.ai/',                       'active'),
    ('万镜一刻',         'wanjing-yike',           '阿里云',      (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-creation'),              '阿里云推出的AI视频创作平台',    '阿里云内测产品，提供从内容解析到故事板生成的一站式方案。',                                                            'https://wanjing.aliyun.com/',                   'active'),
    ('TagoMovie',        'tagomovie',              '比特涌现',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'short-drama-creation'),        '一站式 AI 漫剧与短剧创作平台',  '专为零基础创作者打造，支持小说一键转漫剧/短剧。',                                                                     'https://tagomovie.com/',                        'active'),
    ('灵绘AI',           'linghui-ai',             '灵绘团队',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'short-drama-creation'),        '专业级 AI 短剧漫剧视频创作平台', '提供全流程短剧创作能力，支持都市、古风等多种题材。',                                                                  'https://linghui.ai/',                           'active'),
    ('Pixmax',           'pixmax',                 'Pixmax AI',  (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'short-drama-creation'),        'AI真人短剧、漫剧一站式创作引擎', '首批接入Seedance 2.0满血版，支持高并发、全流程接管创作。',                                                            'https://pixmax.ai/',                            'active'),
    ('Brainrot.mov',     'brainrot-mov',           'Brainrot',   (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-creation'),              '专为创作者打造的AI视频创作平台', '针对社交媒体快节奏内容，支持快速生成病毒式传播视频。',                                                                 'https://brainrot.mov/',                         'active'),
    ('造点AI',           'zaodian-ai',             '阿里巴巴',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'visual-creation'),             '夸克团队推出的AI图像与视频创作平台', '接入Midjourney V7，实现国内领先的音画同步视频生成。',                                                                 'https://ai.quark.cn/',                          'active'),
    ('造次',             'zaoci',                  '造次团队',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-creation'),              'AI原创IP视频社区',             '专为AI视频打造的创作社区，支持创建原创IP与次元世界。',                                                                'https://www.zaoci.tv/',                         'active'),
    ('花生AI',           'huasheng-ai',            '哔哩哔哩',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-creation'),              'B站推出的AI视频创作工具',       '输入文稿或音频，3分钟输出视频，深度适配B站内容创作。',                                                                'https://member.bilibili.com/x/v2/creative/ai-video', 'active'),
    ('VibeKnow',         'vibeknow',               'VibeKnow',   (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'knowledge-video-creation'),    '全球首个 AI 知识视频创作平台',   '将网页、文档、URL转化为清晰的结构化知识视频。',                                                                       'https://www.vibeknow.ai/',                      'active'),
    ('MuseArt AI',       'museart-ai',             'MuseArt',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'visual-creation'),             '一站式 AI 图像和视频创作平台',   '提供全方位的AI视觉创作工具，支持多种生成模式。',                                                                      'https://museart.ai/',                           'active'),
    ('AniShort',         'anishort',               'AniShort',   (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'short-drama-creation'),        'AI短剧协同创作平台',           '以项目为核心，支持编剧、分镜、剪辑多人实时在线协作。',                                                                 'https://anishort.ai/',                          'active'),
    ('献丑AI',           'xianchou-ai',            'SSCMS',      (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-creation'),              '首个 AI 视频开源社区',         '支持视频工作流的分享、复刻与共创，集成多种AI模型。',                                                                   'https://xianchou.ai/',                          'active'),
    ('海螺视频',         'hailuo-video',           'MiniMax',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-generation'),            'MiniMax公司推出的AI视频生成工具', 'MiniMax旗下的视频生成产品，支持将文字创意转化为精美视频。',                                                            'https://hailuoai.com/',                         'active'),
    ('MochiAni',         'mochiani',               'MochiAni',   (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'animation-creation'),          'AI动画视频创作工具',           '致力于用AI技术降低动画创作壁垒，高效转化奇思妙想。',                                                                   'https://www.mochiani.com/',                     'active'),
    ('AdsTurbo AI',      'adsturbo-ai',            'AdsTurbo',   (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-ad-creation'),           'AI视频广告生成平台',           '专注广告领域，自动生成可直接投放的高转化视频素材。',                                                                   'https://www.adsturbo.ai/',                      'active'),
    ('NextCut AI',       'nextcut-ai',             'NextCut',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-creation'),              'AI视频创作工具',               '集成无限画布与剪辑轨道，支持多Agent团队协同创作。',                                                                    'https://nextcut.ai/',                           'active'),
    ('云幕同声',         'yunmu-tongsheng',        '云幕团队',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-localization'),          '专业AI视频翻译工具',           '提供高质量的视频翻译服务，助力短剧与电商内容出海。',                                                                   'https://yunmu.ai/',                             'active'),
    ('萌动AI',           'mengdong-ai',            '萌动团队',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'animation-creation'),          '全球首个二次元/动漫专用 AI 创作工具', '专为动漫爱好者设计，零基础也能一键生成动漫短片。',                                                                    'https://www.mengdong.ai/',                      'active'),
    ('KomikoAI',         'komiko-ai',              'Komiko',     (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'animation-creation'),          '一站式AI动漫内容创作平台',      '支持原创角色创建及视频到动漫风格的转换。',                                                                            'https://komiko.app/',                           'active'),
    ('Keevx',            'keevx',                  '百度',       (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'digital-human-creation'),      '开箱即用的AI数字人视频创作工具',  '百度海外推出的数字人平台，支持URL一键转视频。',                                                                       'https://www.keevx.com/',                        'active'),
    ('即创',             'jichuang',               '字节跳动',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-creation'),              '抖音推出的一站式AI智能创作平台', '深度集成抖音生态，提供全方位的智能创意生产能力。',                                                                     'https://aic.oceanengine.com/',                  'active'),
    ('智谱清影',         'zhipu-qingying',         '智谱AI',     (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-generation'),            '智谱推出的免费AI视频生成工具',   '智谱AI旗下的视频生成产品，提供流畅的高清视频生成体验。',                                                               'https://chatglm.cn/video',                      'active'),
    ('内容特工队',       'content-agent',          NULL,          (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-ad-creation'),           '移动端AI营销视频生成智能体',    '全球首款移动端AI营销视频生成工具，随时随地创作。',                                                                     'https://contentagent.ai/',                      'active'),
    ('磁力开创',         'cili-kaichuang',         '快手',       (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-ad-creation'),           '快手推出的AI创意生产平台',      '快手磁力引擎旗下的AI助手，助力商家高效产出广告素材。',                                                                 'https://creative.kuaishou.com/',                'active'),
    ('A2E',              'a2e',                    'A2E',        (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-generation'),            '一站式AI视频生成平台',          '提供数字人口播、声音克隆、换脸等多种AI视频服务。',                                                                     'https://a2e.ai/',                               'active'),
    ('HitPaw',           'hitpaw',                 'HitPaw',     (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-editing'),               'AI视频、图像和音频处理工具',    '专注于视频画质修复与增强，提供多种专业AI模型。',                                                                       'https://www.hitpaw.com/',                       'active'),
    ('Runway',           'runway',                 'Runway',     (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-generation'),            '领先的AI视频创作工具',          '全球知名的AI视频平台，Gen-3模型具备极高的生成质量。',                                                                  'https://runwayml.com/',                         'active'),
    ('Pika',             'pika',                   'Pika Labs',  (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-generation'),            'AI视频生成和编辑工具',          '支持极具创意的视频生成与编辑，社区活跃度极高。',                                                                       'https://pika.art/',                             'active'),
    ('KreadoAI',         'kreado-ai',              '易点天下',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'digital-human-creation'),      'AI数字人视频营销创作平台',      '专注出海营销，支持140多种语言及数字人克隆。',                                                                          'https://www.kreadoai.com/',                     'active'),
    ('SekoTalk',         'sekotalk',               '商汤科技',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'digital-human-creation'),      'AI对口型视频生成工具',          '业内领先的实时对口型技术，支持多人精准同步。',                                                                         'https://seko.sensetime.com/',                   'active'),
    ('通义灵眸',         'tongyi-lingmou',         '阿里巴巴',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'digital-human-creation'),      '阿里通义推出的AI数字人生产平台',  '阿里通义旗下的数字人产品，专注于商业化视频生产。',                                                                      'https://tongyi.aliyun.com/lingmou/',            'active'),
    ('巨日禄',           'jurilu',                 '巨日禄',      (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'animation-creation'),          '一站式AI动漫视频创作平台',      '针对小说推文赛道，提供从文案到视频的零门槛工具链。',                                                                   'https://video.jurilu.com/',                     'active'),
    ('Medeo',            'medeo',                  'Medeo',      (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-creation'),              'AI视频创作平台',               '无需编辑技能，通过对话即可生成完整可编辑的视频。',                                                                     'https://www.medeo.app/',                        'active'),
    ('Boba',             'boba-video',             'Boba',       (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'animation-creation'),          'AI动漫视频创作工具',           '支持多种动漫风格，具备对话、音效和口型同步功能。',                                                                      'https://www.boba.video/',                       'active'),
    ('Dream Machine',    'dream-machine',          'Luma AI',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-generation'),            'Luma AI推出的AI视频生成工具',   '具备极强的物理规律理解能力，生成视频极其逼真。',                                                                       'https://lumalabs.ai/dream-machine',             'active'),
    ('讯飞绘镜',         'xunfei-huijing',         '科大讯飞',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-generation'),            'AI短视频创作平台',             '讯飞旗下的短视频工具，集成领先的语音与视频生成技术。',                                                                 'https://huijing.xfyun.cn/',                     'active'),
    ('绘想',             'huixiang',               '百度',       (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-creation'),              '百度推出的AI视频创作平台',      '百度旗下的AI视频工具，针对中文语境进行了深度优化。',                                                                   'https://huixiang.baidu.com/',                   'active'),
    ('Hedra',            'hedra',                  'Hedra',      (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'digital-human-creation'),      'AI对口型视频生成工具',          '专注于角色口型同步与动画生成，支持长时长视频。',                                                                       'https://www.hedra.com/',                        'active'),
    ('Vozo',             'vozo',                   'Vozo',       (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-editing'),               '多功能AI视频编辑工具',          '提供视频翻译、配音、口型同步等全方位编辑功能。',                                                                       'https://www.vozo.ai/',                          'active'),
    ('Viggle',           'viggle',                 'Viggle',     (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'digital-human-creation'),      'AI生成可控角色动态视频工具',    '能够精准控制角色的动作与动态，适合创意视频制作。',                                                                      'https://viggle.ai/',                            'active'),
    ('Tavus',            'tavus',                  'Tavus',      (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'digital-human-creation'),      'AI数字人克隆和实时对话工具',    '专注于高度逼真的数字人克隆及低延迟实时对话。',                                                                         'https://www.tavus.io/',                         'active'),
    ('万兴天幕',         'wanxing-tianmu',         '万兴科技',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-generation'),            'AIGC视频创作平台',             '万兴科技推出的音视频多媒体大模型，赋能专业创作。',                                                                      'https://www.wondershare.cn/skyviva.html',       'active'),
    ('妙播',             'miaobo',                 '腾讯',       (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'ecommerce-video-creation'),    'AI直播电商解决方案',            '腾讯广告推出的AI直播工具，助力商家实现24小时直播。',                                                                   'https://miaobo.tencent.com/',                   'active'),
    ('阶跃视频',         'jieyue-video',           '阶跃星辰',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-generation'),            '阶跃星辰推出的AI视频生成工具',   '阶跃星辰旗下的视频生成产品，具备较强的逻辑一致性。',                                                                     'https://www.stepchat.cn/video',                 'active'),
    ('秒创',             'miaochuang',             '新壹科技',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'content-creation'),            'AIGC内容创作平台',             '提供从图文到视频的快速转化能力，适合自媒体创作。',                                                                      'https://shmiao.com/',                           'active'),
    ('元镜',             'yuanjing',               '智灵动力',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-generation'),            'AI短视频创作平台',             '提供从脚本到成片的全流程方案，适配多场景需求。',                                                                       'https://yuanjing.zeelin.cn/',                   'active'),
    ('SkyReels',         'skyreels',               '昆仑万维',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'short-drama-creation'),        'AI短剧创作平台',               '昆仑万维推出的短剧工具，支持60秒以上长视频生成。',                                                                     'https://skyreels.ai/',                          'active'),
    ('MOKI',             'moki',                   '美图',       (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-generation'),            'AI视频短片创作平台',           '美图推出的全流程AI工作流，支持动画、短剧等场景。',                                                                     'https://www.moki.cn/',                          'active'),
    ('神笔马良',         'shenbi-maliang',         '猫眼娱乐',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-creation'),              'AI影视创作生成工具',           '专为长剧本解析打造，实现从剧本到动态故事板的转化。',                                                                   'https://shenbi.maoyan.com/',                    'active'),
    ('Video Ocean',      'video-ocean',            '潞晨科技',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-generation'),            '多功能AI视频生成平台',          '基于Open Sora开源项目，提供电影级特效生成能力。',                                                                      'https://video-ocean.com/',                      'active'),
    ('Flow Studio',      'flow-studio',            'Google',     (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-generation'),            'AI长视频生成工具',             'Google推出的AI电影制作工具，基于Veo大模型。',                                                                          'https://labs.google/fx/tools/flow',             'active'),
    ('Vizard',           'vizard',                 'Vizard',     (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-editing'),               '长视频转短视频AI工具',         '智能识别长视频精彩片段，快速生成适合社媒的短视频。',                                                                    'https://vizard.ai/',                            'active'),
    ('寻光',             'xunguang',               '阿里巴巴',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-creation'),              '全流程AI视频创作平台',         '达摩院研发，以PPT制作方式创作视频，高可控性。',                                                                        'https://xunguang.com/',                         'active'),
    ('Hotshot',          'hotshot',                'Hotshot',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-generation'),            'AI视频生成工具',               '支持将文本快速转化为高质量、逼真的短视频。',                                                                            'https://hotshot.ai/',                           'active'),
    ('vivago.ai',        'vivago-ai',              'HiDream.ai', (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-generation'),            '免费AI视频生成和图像创作平台',  '聚合Sora、Kling等顶级模型，提供免费的视频生成服务。',                                                                  'https://vivago.ai/',                            'active'),
    ('Humva',            'humva',                  'Humva',      (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'digital-human-creation'),      'AI数字人生成工具',             '将脚本转化为带虚拟演示者的专业视频，支持自定义形象。',                                                                  'https://humva.ai/',                             'active'),
    ('D-ID',             'd-id',                   'D-ID',       (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'digital-human-creation'),      'AI真人口播视频生成工具',       '全球知名的口播视频生成平台，支持照片一键变视频。',                                                                     'https://www.d-id.com/',                         'active'),
    ('Stable Video',     'stable-video',           'Stability AI', (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-generation'),           'AI视频生成工具',               'Stability AI推出的视频生成产品，支持多种创意控制。',                                                                    'https://www.stablevideo.com/',                  'active'),
    ('OneStory',         'onestory',               '创壹科技',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'content-creation'),            '专业的AI故事生成助手',         '帮助零门槛创作故事影集，将灵感一键转化为故事板。',                                                                      'https://onestory.art/',                         'active'),
    ('Noisee AI',        'noisee-ai',              '月之暗面',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-generation'),            'AI音乐视频MV生成工具',         '将音频转化为具有节奏感和风格化的音乐MV。',                                                                             'https://noisee.ai/',                            'active'),
    ('万兴播爆',         'wanxing-bobao',          '万兴科技',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'digital-human-creation'),      'AI数字人口播视频营销工具',     '针对出海营销场景，提供海量素材与数字人口播能力。',                                                                      'https://virbo.wondershare.cn/',                 'active'),
    ('Vimi',             'vimi',                   '商汤科技',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'digital-human-creation'),      '可控人物视频生成AI模型',       '实现对人物表情与肢体动作的全控制，生成长达分钟级视频。',                                                                'https://www.sensetime.com/cn/product-vimi',     'active'),
    ('Etna',             'etna',                   '七火山科技',  (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-generation'),            'AI文生视频工具',               '具备极强的时空连续性处理能力，支持高质量视频输出。',                                                                    'https://www.7volcanoes.com/etna',               'active'),
    ('艺映AI',           'yiying-ai',              '艺映团队',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-creation'),              'AI视频创作工具',               '支持文生视频、图生视频及极具特色的视频转漫画功能。',                                                                   'https://www.artink.art/',                       'active'),
    ('LensGo',           'lensgo',                 'LensGo',     (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-creation'),              'AI视频创作工具',               '支持文本/图片生成视频，特别擅长风格转换与人物替换。',                                                                   'https://lensgo.ai/',                            'active'),
    ('必剪Studio',       'bijian-studio',          '哔哩哔哩',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'digital-human-creation'),      '免费AI数字分身定制和视频创作工具', 'B站官方出品，免费提供高保真数字分身与音色定制。',                                                                      'https://bcut.bilibili.cn/',                     'active'),
    ('度加创作工具',     'dujia-creator',          '百度',       (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'content-creation'),            '百度官方出品的AIGC创作平台',   '百度旗下全能型创作工具，支持从灵感到成片的全流程。',                                                                    'https://aigc.baidu.com/',                       'active'),
    ('WinkStudio',       'winkstudio',             '美图',       (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-editing'),               '桌面端AI视频剪辑工具',         '专注于视频美容与画质修复，提供专业级AI编辑能力。',                                                                     'https://wink.meitu.com/',                       'active'),
    ('VMagic',           'vmagic',                 'VMagic',     (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-editing'),               'AI视频处理平台',               '提供视频风格转换、换脸、照片舞蹈等多种趣味功能。',                                                                      'https://www.vmagic.app/',                       'active'),
    ('讯飞虚拟人',       'xunfei-virtual-man',     '科大讯飞',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'digital-human-creation'),      '全栈式AI虚拟人应用服务平台',    '提供从形象构建到驱动交互的全栈虚拟人解决方案。',                                                                        'https://virtual-man.xfyun.cn/',                 'active'),
    ('飞影数字人',       'feiying-digital-human',  '飞影团队',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'digital-human-creation'),      'AI数字人创作平台',             '支持10秒拍摄生成专属数字分身，还原度极高。',                                                                            'https://hifly.cc/',                             'active'),
    ('Video Studio',     'video-studio',           NULL,          (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-creation'),              '在线AI视频制作工具',           '旨在让零编辑技能的用户也能制作出专业级视频内容。',                                                                      'https://videostudio.ai/',                       'active'),
    ('Pixfun',           'pixfun',                 'Pixfun',     (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'animation-creation'),          '一站式动画故事AI视频生成平台',  '专为YouTube/TikTok设计，支持快速生成动画叙事内容。',                                                                    'https://app.pixfun.ai/',                        'active'),
    ('Decohere',         'decohere',               'Decohere',   (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'video-generation'),            'AI视频生成平台',               '提供极速的视频生成体验，支持角色一致性控制。',                                                                          'https://www.decohere.co/',                      'active'),
    ('YoYo',             'yoyo-video',             '鹿影科技',    (SELECT id FROM ai_product_types WHERE slug = 'ai-video-tools'), (SELECT id FROM ai_use_cases WHERE slug = 'animation-creation'),          '二次元动漫视频AI创作平台',     '专注于二次元领域，提供丰富的动漫素材与生成能力。',                                                                      'https://www.yoyo.video/',                       'active')
ON CONFLICT (slug) DO NOTHING;

-- -----------------------------------------------------------
-- 验证
-- -----------------------------------------------------------
DO $$
BEGIN
    RAISE NOTICE 'ai_product_types : %', (SELECT count(*) FROM ai_product_types);
    RAISE NOTICE 'ai_use_cases     : %', (SELECT count(*) FROM ai_use_cases);
    RAISE NOTICE 'ai_tools         : %', (SELECT count(*) FROM ai_tools);
END $$;

COMMIT;
